image: registry.gitlab.com/ratio-case-os/docker/rust-ci

variables:
  FLAMES: ""

stages:
  - test
  - deploy

rust-lint:
  stage: test
  script:
    - just check

rust-lint-full:
  stage: test
  allow_failure: true
  script:
    - just check-all

rust-deploy:
  stage: deploy
  only:
    refs:
      - main
  script:
    - rust-ci publish-lib
  allow_failure: true
